package com.tverts.exec;

/**
 * Execution error. Generated by
 * {@link Executor}s only.
 *
 * @author anton.baukin@gmail.com
 */
public class ExecError extends RuntimeException
{
	/* public: constructor */

	public ExecError(Executor executor, String message)
	{
		super(message);
		this.executor = executor.getName();
	}

	public ExecError(Executor executor, Throwable e, String message)
	{
		super(message, e);
		this.executor = executor.getName();
	}

	public ExecError(Executor executor, Throwable e)
	{
		super(e);
		this.executor = executor.getName();
	}


	/* public: ExecError interface */

	public String getExecutor()
	{
		return executor;
	}


	/* private: the executor */

	private String executor;
}
