package com.tverts.endure;

/**
 * Marker interface telling that entity (implementing it)
 * has the keys generated by Primary Keys Generator obtained via
 * {@link com.tverts.endure.keys.KeysPoint#getPrimaryGenerator()}.
 *
 * @author anton.baukin@gmail.com
 */
public interface PrimaryIdentity extends NumericIdentity
{}